### ISSUE TITLE
Access enter value to get last view controller receive 

### ISSUE THREAD

**Issue by indrajeetgaikwad** [vladislovshilov/StepView#1]
I am use this Stepview. I have  six view controller, every controller had one textfield to entering inputs 
my operation is to operate in last view controller to access every controller insert values to getting in last viewcontroller

**Comment by vladislovshilov** [comment]
Hi, @indrajeetgaikwad. Thank you for your interesting in my library. 
Unfortunately, it provides only a view with steps. Communication logic between controllers you should write by yourself.
For example you can use Delegation pattern or pass the data through the segue. You can read about this here [https://stackoverflow.com/questions/26207846/pass-data-through-segue](url)
Also you can use more complexity way like Routers or Coordinator and pass data through this classes.
Hope I helped you, good luck!

**Comment by vladislovshilov** [comment]
Seems like I solved you problem, I will close the issue.
